### ISSUE TITLE
Error when i try to send snap

### ISSUE THREAD

**Issue by ricoxor** [agermanidis/SnapchatBot#23]
When i use the ReflectorBot.py i have this error : 

```
[2015-03-02 12:21:30,710] [ReflectorBot-781b] Uploading snap 219131425295190212r
[2015-03-02 12:21:30,717] Starting new HTTPS connection (1): feelinsonice-hrd.ap
pspot.com
[2015-03-02 12:21:31,171] "POST /bq/upload HTTP/1.1" 401 None

Traceback (most recent call last):
  File "C:\Users\RMC\Desktop\SnapchatBot-master\examples\reflectorbot.py", line
18, in <module>
    bot.listen(timeout=5)
  File "build\bdist.win32\egg\snapchat_bots\bot.py", line 58, in listen
  File "C:\Users\RMC\Desktop\SnapchatBot-master\examples\reflectorbot.py", line
7, in on_snap
    self.send_snap([sender], snap)
  File "build\bdist.win32\egg\snapchat_bots\bot.py", line 91, in send_snap
  File "build\bdist.win32\egg\snapchat_bots\snap.py", line 40, in upload
  File "build\bdist.win32\egg\pysnap\__init__.py", line 360, in upload
  File "build\bdist.win32\egg\pysnap\__init__.py", line 83, in _request
  File "build\bdist.win32\egg\pysnap\utils.py", line 88, in request
  File "C:\Python27\lib\site-packages\requests-2.5.3-py2.7.egg\requests\models.p
y", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized
```

**Comment by ricoxor** [comment]
The snapchat account was not configured.
