### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden

### ISSUE THREAD

**Issue by ricoxor** [agermanidis/SnapchatBot#24]
When i try the bot i have this message :

```
C:\Users\root\Desktop\FeedMySnap\examples>storifierbot.py
[2015-03-02 15:51:41,038] Starting new HTTPS connection (1): feelinsonice-hrd.ap
pspot.com
[2015-03-02 15:51:41,490] "POST /bq/login HTTP/1.1" 403 434
Traceback (most recent call last):
  File "C:\Users\root\Desktop\FeedMySnap\examples\storifierbot.py", line 10, in
<module>
    bot = StorifierBot('sharetogether', 'password')
  File "build\bdist.win32\egg\snapchat_bots\bot.py", line 20, in __init__
  File "build\bdist.win32\egg\pysnap\__init__.py", line 100, in login
  File "build\bdist.win32\egg\pysnap\__init__.py", line 83, in _request
  File "build\bdist.win32\egg\pysnap\utils.py", line 88, in request
  File "C:\Python27\lib\site-packages\requests-2.5.3-py2.7.egg\requests\models.p
y", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden
```

**Comment by Sh1eld** [comment]
Uh, I'd say to make sure that your username and password are correct to begin and furthermore make sure your IP/the account isn't blacklisted/blocked/banned/etc.

A 403 error is raised because it received the request but for some reason forbid you, hence "Forbidden", however I can't pinpoint the exact reason for you and giving you some things to try out which may result in a solution.

**Comment by Rob--** [comment]
Try this:

snapchat.com/unlock

**Comment by ricoxor** [comment]
My server is ban, i don't know why, it's a new one...
I try to change my IP

**Comment by blendom** [comment]
I also got this error, and I haven't never hosted bot in my ip.
Could there be something wrong in feelingsonice-hrd.appspot.com?

Im trying to run it on raspberry pi
I got some errors before, but got this after reinstalling all depencies+python+pip

**Comment by Rob--** [comment]
Also have this problem, it's possible our IP was banned. This happened before and we switched our server from London to NY. We're switching again to SF and we'll see if this resolves the problem or if there's a problem with the API.

**Comment by N07070** [comment]
It seems our IPs are banned. Time to TOR.
