### ISSUE TITLE
IOError: Decoder jpeg not available

### ISSUE THREAD

**Issue by ObjectiveTruth** [agermanidis/SnapchatBot#25]
Hey Fellas, I got this error on the first snap I sent to my bot using the example reflectorbot
```
Traceback (most recent call last):
  File "reflectorbot.py", line 23, in <module>
    bot.listen(timeout=42)
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 54, in listen
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 132, in get_snaps
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 45, in process_snap
  File "build/bdist.linux-x86_64/egg/snapchat_bots/snap.py", line 70, in __init__
  File "build/bdist.linux-x86_64/egg/snapchat_bots/utils.py", line 40, in resize_image
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 1793, in thumbnail
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 1536, in resize
  File "build/bdist.linux-x86_64/egg/PIL/ImageFile.py", line 200, in load
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 417, in _getdecoder
IOError: decoder jpeg not available
```
I'm running on Ubuntu with python 2.7

I have imageMagick and FFMPEG installed and are both on my path
```
identify -version
ffmpeg
```
These can both be run from anywhere on the system. Not sure what might be wrong?

**Comment by ObjectiveTruth** [comment]
I think I fixed it, had to install a pillow dependency
```
 sudo apt-get install libjpeg-dev
```

**Comment by agermanidis** [comment]
I changed the readme to mention libjpeg. Thanks!

**Comment by ObjectiveTruth** [comment]
Incase anyone finds this thread, these were the steps I took
* upgraded PIP

```easy_install -U pip```
* Uninstalled PIL and Pillow

```pip uninstall PIL
pip uninstall Pillow```
* Installed libjpeg-dev

```apt-get install libjpeg-dev```
* Installed Pillow

```pip install Pillow```
