### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by ricoxor** [agermanidis/SnapchatBot#27]
I have this error only on my server not on local

```
[2015-03-04 14:36:41,358] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
[2015-03-04 14:36:41,875] "POST /bq/upload HTTP/1.1" 401 None

Traceback (most recent call last):
  File "C:\Users\root\Desktop\FeedMySnap\storifierbot.py", line 11, in <module>    bot.listen()
  File "C:\Users\root\Desktop\FeedMySnap\snapchat_bots\bot.py", line 66, in listen    self.on_snap(snap.sender, snap)
  File "C:\Users\root\Desktop\FeedMySnap\storifierbot.py", line 7, in on_snap    self.post_story(snap)
  File "C:\Users\root\Desktop\FeedMySnap\snapchat_bots\bot.py", line 113, in post_story    snap.upload(self)
  File "C:\Users\root\Desktop\FeedMySnap\snapchat_bots\snap.py", line 40, in upload    self.media_id = bot.client.upload(self.file.name)
  File "build\bdist.win32\egg\pysnap\__init__.py", line 360, in upload    }, files={'data': encrypt(data)})
  File "build\bdist.win32\egg\pysnap\__init__.py", line 83, in _request    raise_for_status, req_type)
  File "build\bdist.win32\egg\pysnap\utils.py", line 88, in request   r.raise_for_status()
  File "C:\Python27\lib\site-packages\requests-2.5.3-py2.7.egg\requests\models.py", line 831, in raise_for_status   raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized
```

I'm using proxy, it's not my IP or my account :/

**Comment by enstulen** [comment]
How did you solve this?

**Comment by ricoxor** [comment]
Yes by addding a proxy
