### ISSUE TITLE
Can't guess type of snap in bot.

### ISSUE THREAD

**Issue by N07070** [agermanidis/SnapchatBot#44]
Hey, 

I'm trying to do a little something with my bot. To do that, I need to get the type of the snap. Altough, I cannot import `utils` . Could you help me ?

```
# Import the classes
from snapchat_bots import SnapchatBot, Snap
from argparse import ArgumentParser
import os, sys, time
sys.path.insert(0, '/media/HDD/Code/Python/SnapchatBot/snapchat_bots')
from utils import guess_type

# To add the snap to the story, and watermark it with the username
    def on_snap(self, sender, snap):
        # Temp save of the snap
        snap.save("temporaire")
        self.log("Saved the snap.")
        media_type = guess_type("temporaire")
        
        # If the snap is an image
        if media_type is MEDIA_TYPE_IMAGE:
            os.system('convert temporaire -size 1080x1920 -gravity South -fill grey -pointsize 80 label:"'+str(sender)+'" image.jpg')
            try:
                self.post_story(Snap.from_file('image.jpg'))
                self.log("Posted the snap in the story !")
            except: 
                self.send_snap(sender, Snap.from_file('resources/erreur.png'))
                self.log("Error while trying to post the snap !")
                pass
            os.system('rm image.jpg temporaire')
            try:
                if sender != args.username:    
                    self.send_snap(sender, Snap.from_file('resources/recu.png'))
                    self.log("Validated the reception !")
            except:
                pass
        # If the snap is a video
        elif media_type is MEDIA_TYPE_VIDEO or media_type is MEDIA_TYPE_VIDEO_WITHOUT_AUDIO and os.path.getsize("temporaire") != 0:
            os.system('ffmpeg -i temporaire -vf drawtext="fontfile=resources/Arial.ttf: text='+str(sender)+':fontcolor=dimgray@1.0:fontsize=00:x=00: y=00" -y output.mp4')
            try:
                self.post_story(Snap.from_file('output.mp4'))
                self.log("Posted the snap in the story !")
            except: 
                self.send_snap(sender, Snap.from_file('resources/erreur.png'))
                self.log("Error while trying to post the snap !")
                pass
            os.system('rm output.mp4 temporaire')
            try:
                if sender != args.username:    
                    self.send_snap(sender, Snap.from_file('resources/recu.png'))
                    self.log("Validated the reception !")
            except:
                pass
        # En cas d'erreur
        else:
            self.send_snap(sender, Snap.from_file('resources/erreur.png'))
            self.log("Error while trying to post the snap !")
```

The error is : 

```
Traceback (most recent call last):
  File "fbstory-dev.py", line 143, in <module>
    bot.listen()
  File "/media/HDD/Code/Python/SnapchatBot/snapchat_bots/bot.py", line 66, in listen
    self.on_snap(snap.sender, snap)
  File "fbstory-dev.py", line 55, in on_snap
    media_type = guess_type("temporaire")
  File "/media/HDD/Code/Python/SnapchatBot/snapchat_bots/utils.py", line 23, in guess_type
    if is_video_file(path): return MEDIA_TYPE_VIDEO
  File "/media/HDD/Code/Python/SnapchatBot/snapchat_bots/utils.py", line 28, in is_video_file
    return mimetypes.guess_type(path)[0].startswith("video")
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Thanks !

**Comment by agermanidis** [comment]
`snap.media_type`

**Comment by N07070** [comment]
I'm sorry, but I don't seem to understand ? Could you explain or give an exemple please ? :smile:

**Comment by agermanidis** [comment]
You can access the snap's type by doing `snap.media_type`. The `guess_type`
function is internal and is not meant to be used externally.

On Sat, Mar 14, 2015 at 7:00 PM, N07070 <notifications@github.com> wrote:

> I'm sorry, but I don't seem to understand ? Could you explain or give an
> exemple please ? [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agermanidis/SnapchatBot/issues/44#issuecomment-80754389>
> .
>



-- 
Anastasis Germanidis
(860) 807-5860

**Comment by agermanidis** [comment]
In your example:

```python
def on_snap(self, sender, snap):
        # Temp save of the snap
        snap.save("temporaire")
        self.log("Saved the snap.")
        media_type = snap.media_type
```

**Comment by N07070** [comment]
Perfect ! Do you think it's time to write a wiki for the lib ? It's getting pretty big, and very usefull to al lot of people.
