### ISSUE TITLE
KeyError: 'updates_response' bot.py line 27

### ISSUE THREAD

**Issue by ShaneIsrael** [agermanidis/SnapchatBot#52]
I suddenly started getting this error today and I haven't made any changes to the code. My bot has been running fine for quite a while until I tried to restart it today and now it gets that error. 

http://i.imgur.com/jEq3koR.png

Any account I try to log in with the bot gets that error.

**Comment by ShaneIsrael** [comment]
I'm guessing Snapchat made another change on their end, I installed the latest pysnap and still get the issue.

**Comment by agermanidis** [comment]
Yeah, definitely a change on Snapchat's end -- probably some additional fields that weren't required by `/loq/login` before now are. We need to completely document the new API to make sure we're making the right requests.

**Comment by mavieth** [comment]
Has there been any updates on how we could go about fixing this?

**Comment by N07070** [comment]
Also had this error.

**Comment by koushag** [comment]
Is there a way I can bypass this problem until someone fixes it?

**Comment by N07070** [comment]
Not really, we need to wait for @agermanidis to fix it. Want dogecoin ?

**Comment by jcherrera** [comment]
@koushag @N07070 I had it working last night and this morning, and it was until Today that I started getting this error.

I tried running it on a linux vm and on mac osx and had the same problem, is snapchat filtering specific accounts?

**Comment by mavieth** [comment]
...So what now?

**Comment by agermanidis** [comment]
I'll take a look and try to figure out how to solve it when I find the time.

**Comment by misingnoglic** [comment]
I am still getting this issue now

**Comment by red-green** [comment]
Dang it, Snapchat! Why do you have to do this to me???

**Comment by Jfach** [comment]
I think there should be some sort of failing tag added to the repo, unless anyone is successfully running it without getting the updates_response error. This would prevent the unnecessary duplicates from being opened

**Comment by jcherrera** [comment]
I went into the snapchat account I was using with this bot, and I had a message from snapchat saying that I was putting myself and others at risk for using a third-party application to access SC.

**Comment by sverrejb** [comment]
Is this fixed? I got this error today.

**Comment by red-green** [comment]
As has been pointed out, Snapchat is likely actively changing their api to prevent us from using it.

**Comment by krissrex** [comment]
The issue may be simpler than we think. The key <code>updates_response</code> does not exist, because snapchat replies with:
```python
{u'message': u"You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!", u'logged': False}
```
I will try updating the client header and see how this goes.

**Comment by N07070** [comment]
They might be a solution after all ?

**Comment by krissrex** [comment]
Yes, there is a solution, but it is not easy. Either use the android system and generate the required keys, or reverse engineer the iOS-app for discover how the hash is computed. 
I see some PHP-libraries used the android-solution.

**Comment by N07070** [comment]
Should I just try random user-agents ? Also, do you have an ideal of how
to use the android system and generate the required keys ?

**Comment by krissrex** [comment]
@N07070 
> Should I just try random user-agents ?

That would not work. Either you use an old one, to which Snapchat API responds with "too old client", or you use a new one which requires more info.

> Also, do you have an ideal of how to use the android system and generate the required keys ?

You would need to use a google account to send a request for OAuth2 tokens, using snapchats package name, I believe. 

I read about this in another github issue for the PHP library. They said that once you had a request, it was easy to repeat it and generate new keys for that specific user in the future. They discussed this around January to March 2015. [Link to discussion](https://github.com/JorgenPhi/php-snapchat/issues/89)

However, this requires you to own an android phone (or possibly use an emulator? They all share device ID though. Perhaps it can be changed?), and you must have a google account (gmail).

**Comment by krissrex** [comment]
The iOS way of authentication is perhaps easier from both a python and user perspective, as it only requires a hash. However, iOS apps are encrypted, and most likely reversed to an assembly-like language. This makes it hard to discover how the hash is generated in the first place.

And we ultimately dont know what the hash consists of. It is based on guesses that it only uses user/password/tokens from the Snapchat API alone.

**Comment by N07070** [comment]
I have an Android Phone at my disposal. Now, as for the OAuth part, I
would need more info, because I am good with python, but Java and
Android, not so much....

**Comment by N07070** [comment]
Okay, I looked through the php code. So, now, could @agermanidis make an update as the provided solution seems to work in php, could you port it to python ?

**Comment by brorbw** [comment]
I get a 403 on the login request 
```
[2017-09-26 19:58:56,005] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
[2017-09-26 19:58:56,392] https://feelinsonice-hrd.appspot.com:443 "POST /loq/login HTTP/1.1" 403 None
Traceback (most recent call last):
  File "storifierbot.py", line 16, in <module>
    bot = StorifierBot(args.username, args.password)
  File "/usr/local/lib/python2.7/dist-packages/snapchat_bots/bot.py", line 27, in __init__
    self.auth_token = result['updates_response']['auth_token']
KeyError: 'updates_response'
```
