### ISSUE TITLE
IOError: File not open for writing

### ISSUE THREAD

**Issue by csu** [agermanidis/SnapchatBot#54]
```
[2015-03-22 22:22:51,092] "POST /bq/blob HTTP/1.1" 200 1620640
Traceback (most recent call last):
  File "csebot.py", line 34, in <module>
    bot.listen(timeout=60)
  File "build/bdist.macosx-10.10-intel/egg/snapchat_bots/bot.py", line 62, in listen
  File "build/bdist.macosx-10.10-intel/egg/snapchat_bots/bot.py", line 172, in get_snaps
  File "build/bdist.macosx-10.10-intel/egg/snapchat_bots/bot.py", line 146, in process_snaps
  File "build/bdist.macosx-10.10-intel/egg/snapchat_bots/bot.py", line 53, in process_snap
  File "build/bdist.macosx-10.10-intel/egg/snapchat_bots/snap.py", line 93, in __init__
IOError: File not open for writing
```

**Comment by jfremstad** [comment]
I have the same problem, and I've noticed that this only happens if the bot receives a videosnap from certain phones.

**Comment by jcherrera** [comment]
I get the same error with certain videosnaps, is there anyway to disable all videosnaps? So only photosnaps are used?

**Comment by krissrex** [comment]
I guess it is because line 86 in snap.py should use rb+ instead of rb.
```python
                self.file = open(video_filename, 'rb+')
```

**Comment by csu** [comment]
Thanks @krissrex!

**Comment by stamplong** [comment]
thanks @krissrex first use GitHub reply message，thanks

**Comment by stamplong** [comment]
use use
