### ISSUE TITLE
Updated Responses

### ISSUE THREAD

**Issue by mavieth** [agermanidis/SnapchatBot#58]
How can I help making the Snapchat bot work again?

**Comment by koushag** [comment]
also looking for a way to help :+1:

**Comment by N07070** [comment]
We need to get someone to help. Would a bounty help @agermanidis make this working again ?

**Comment by agermanidis** [comment]
I'm working on a fix, but I'm starting to suspect that Snapchat is actually looking at repos like this and updating their backend to block us. And I'm not sure I want to play this endless cat-and-mouse game.

**Comment by N07070** [comment]
Well, you could make it private and invite-only ?

**Comment by mavieth** [comment]
That would be a pretty cool solution. Any thoughts @agermanidis?

**Comment by bl3ndom** [comment]
If there is anything to do, please inform us!

**Comment by red-green** [comment]
We need to convince Snapchat that APIs are a good idea....

**Comment by gerbill** [comment]
So there's no more API for SnapChat?

**Comment by red-green** [comment]
@gerbill there is, it's undocumented, but they keep changing it to stop people from making bots.

**Comment by gerbill** [comment]
how often do they change it?

**Comment by justinoreilly** [comment]
After finally getting up and running i am getting this same error. Any update on a new break through?

**Comment by edgarZD** [comment]
Any luck with this? I'm getting the following:

[2015-04-28 15:24:36,548] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
/Library/Python/2.7/site-packages/requests-2.6.2-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[2015-04-28 15:24:44,810] "POST /loq/login HTTP/1.1" 200 None
Traceback (most recent call last):
  File "examples/storifierbot.py", line 16, in <module>
    bot = StorifierBot(args.username, args.password)
  File "build/bdist.macosx-10.9-intel/egg/snapchat_bots/bot.py", line 27, in __init__

**Comment by justinoreilly** [comment]
No luck on my end yet.

Sent from my iPhone

On Apr 28, 2015, at 18:28, edgarZD <notifications@github.com<mailto:notifications@github.com>> wrote:


Any luck with this? I'm getting the following:

[2015-04-28 15:24:36,548] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com<http://feelinsonice-hrd.appspot.com>
/Library/Python/2.7/site-packages/requests-2.6.2-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning
[2015-04-28 15:24:44,810] "POST /loq/login HTTP/1.1" 200 None
Traceback (most recent call last):
File "examples/storifierbot.py", line 16, in
bot = StorifierBot(args.username, args.password)
File "build/bdist.macosx-10.9-intel/egg/snapchat_bots/bot.py", line 27, in init

-

**Comment by fredghostkyle** [comment]
@justinoreilly @red-green @N07070 @agermanidis Any updates?

**Comment by red-green** [comment]
Because if recent changes and pushes toward commercialization I'm the recent update, It's not likely Snapchat will allow third party apps that don't involve "discover". Even if we do figure out this api, they'll just change it again.

**Comment by fredghostkyle** [comment]
@red-green Well darn then. Do you know of any out there that are working right now?

**Comment by red-green** [comment]
@fredghostkyle nope sorry :disappointed:

**Comment by fredghostkyle** [comment]
@red-green darn, all I wanted to do was raise my snap story. Ohh well :P better luck when SnapChat see that power that 3rd party apps have.

**Comment by mzaboss** [comment]
Full Snapchat API using a new and complex tweak.

You can use it to:

Create snapchat bots.

* Features:

# Send a media to a story
# Send a snap
# Add a friend
# Delete a friend
# Mark a snap video as viewed

Create a third app on the App Store or Play Store.

more dev informations will be sent in PDF.

Monthly subscription: $450! only. Unlimited requests to snapchat.

FREE 24h trial!

Skype: mzaboss

Thank you,
regards.
