### ISSUE TITLE
Please create guide for how to set this up with ubuntu or centos

### ISSUE THREAD

**Issue by justinoreilly** [agermanidis/SnapchatBot#59]
Trying to get the dependancies correct has been an absolute nightmare.

**Comment by blendom** [comment]
True, I had to install everything at least 6 times and then it just worked.

**Comment by mavieth** [comment]
Does it work now?

**Comment by justinoreilly** [comment]
Here is that I get in my console when I try to install.
http://pastebin.com/r34q11L4

**Comment by justinoreilly** [comment]
I have managed to make it work but I am stonewalled by needing updated responses.

**Comment by mavieth** [comment]
You try installing:

sudo pip install requests==2.5.3

That was a previous fix, not sure about now. What is your error message?

**Comment by justinoreilly** [comment]
[root@xmpp examples]# python storifierbot.py -u ********** -p *************
[2015-04-17 12:53:21,595] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
/usr/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[2015-04-17 12:53:22,119] "POST /loq/login HTTP/1.1" 200 None
Traceback (most recent call last):
  File "storifierbot.py", line 16, in <module>
    bot = StorifierBot(args.username, args.password)
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 27, in __init__
KeyError: 'updates_response'

**Comment by Samze** [comment]
You could always run the bot in a docker container. I created a Dockerfile that installs all dependencies, so you don't have to - check it out.
https://github.com/Samze/SnapchatBot-docker

If you a set of instructions that allow you to install dependencies on your ubuntu machine, you can always check out the instructions in the Dockerfile.
https://github.com/Samze/SnapchatBot-docker/blob/master/Dockerfile
