### ISSUE TITLE
Setup.py won't run

### ISSUE THREAD

**Issue by alex742** [agermanidis/SnapchatBot#62]
The error that comes up is:

Traceback (most recent call last):
  File "C:\Users\Alex\Desktop\Python\snapbot\SnapchatBot-master\setup.py", line 24, in <module>
    license=open('LICENSE').read()
  File "C:\Python32\lib\distutils\core.py", line 109, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Python32\lib\distutils\dist.py", line 257, in __init__
    warnings.warn(msg)
  File "C:\Python32\lib\idlelib\PyShell.py", line 59, in idle_showwarning
    file.write(warnings.formatwarning(message, category, filename,
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by N07070** [comment]
You might want to update all your python install, can't reproduce. Also, please note that this repo is dead, the bots don't work anymore.

**Comment by drewsefolson** [comment]
but what about https://github.com/agermanidis/SnapchatBot/issues/6#issuecomment-75419682 ??? have you made any progress on the project
