### ISSUE TITLE
Key Error?

### ISSUE THREAD

**Issue by AlphaT3ch** [agermanidis/SnapchatBot#63]
[2016-04-29 23:15:09,223] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com
[2016-04-29 23:15:09,605] "POST /loq/login HTTP/1.1" 200 None
Traceback (most recent call last):
  File "reflectorbot.py", line 22, in <module>
    bot = ReflectorBot(args.username, args.password)
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 27, in __init__
KeyError: 'updates_response'

**Comment by Jfach** [comment]
@AlphaT3ch Unfortunately this repo is deprecated and no longer works with the Snapchat API.

**Comment by AlphaT3ch** [comment]
@Jfach Yeah, just realizing that. It seems that all of them are turning up that way. Any clue where to find a working one? At this point, I don't even care what language, I could port it myself.

**Comment by Rob--** [comment]
@AlphaT3ch I believe [this](https://github.com/mgp25/SC-API) guy has somehow got the Snapchat API to work but he is proxying all requests and his work isn't open source. I believe it is also not free, so good luck. I don't know of any working libraries at the moment, I believe Snapchat have privatised their API and from what I remember last time I tried to document their new API is that it's very hard (tried about 6 months ago). You could try making your own library if you manage to get anywhere.

**Comment by drewsefolson** [comment]
@Rob-- I believe @Snowlav may be making a library, I think he may have completed it. but dont quote me on that 

sources:
https://github.com/agermanidis/SnapchatBot/issues/6#issuecomment-75419682

**Comment by Rob--** [comment]
@drewsefolson I've seen no progress in open source work to access Snapchat's private API, from what I can remember I think a special key needs to be generated that's used either to sign requests or is passed along as a parameter but it's incredibly hard to get this key (https://github.com/fisch0920/snapchat/issues/29), one guy (I think it's Liam, https://github.com/liamcottle) runs Casper and knows how to generate the key but it is a paid and private service.

**Comment by drewsefolson** [comment]
@Rob-- Well actually I have been tried to get in touch with Liam on and off for a while. My thought was becuase I am currently a Computer Science student of Stanford University and I would like to use the api to do some work on a project, but my school isnt granting me the funds so hopefully he will understand and grant me access at least for a little while. he seems like a nice enough guy.

**Comment by drewsefolson** [comment]
@Rob-- if I do get access to the will snapchatbot still work? Or do you think I will need to do a little touch up work to the project

**Comment by Rob--** [comment]
@drewsefolson if you do get access, you won't be able to use this library as it's not built around Casper. You could try using the NodeJS library I linked which is built around the Casper API but you might need to update it to work.

Or you could try investigating the API yourself and see if you get anywhere!
