### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by joveice** [agermanidis/SnapchatBot#65]
Traceback (most recent call last):
  File "googlerbot.py", line 1, in <module>
    import time, requests, tempfile, urlparse, os, boto, uuid, re
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 60, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 14, in <module>
    from . import sessions
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 27, in <module>
    from .adapters import HTTPAdapter
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 28, in <module>
    from .packages.urllib3.exceptions import NewConnectionError
ImportError: cannot import name NewConnectionError

**Comment by nathanallen32** [comment]
I don't understand anything. I try to make a sender bot like one that spams ppl. But when I do I forget to put two ='s and I have to start over cuz of Python.... Did u figure out how to do anything?

**Comment by menonmoon** [comment]
You figure out how to make a spambot yet
