### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by nisutec** [agermanidis/SnapchatBot#67]
Why i recive thies error ?

root@vps-zap59814x-4:~/SnapchatBot-master/examples# python reflectorbot.py -u noxxxxx -p 19wr#%xxxxxxxxx
[1] 21608
-bash: FeFOZyU9T@T2YRyUR%SxPz%Sg7vOCrdg5: command not found
root@vps-zap59814-4:~/SnapchatBot-master/examples# [2018-12-05 11:02:36,165] Starting new HTTPS connection (1): feelinsonice-hrd.appspot.com:443
[2018-12-05 11:02:36,536] https://feelinsonice-hrd.appspot.com:443 "POST /loq/login HTTP/1.1" 400 None
Traceback (most recent call last):
  File "reflectorbot.py", line 22, in <module>
    bot = ReflectorBot(args.username, args.password)
  File "build/bdist.linux-x86_64/egg/snapchat_bots/bot.py", line 26, in __init__
  File "/usr/local/lib/python2.7/dist-packages/requests-2.20.1-py2.7.egg/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by rydeom** [comment]
I have the same error and without any idea how to fix it. Did anybody got a fix?

**Comment by SamKingDev** [comment]
First line in the readme

"This repo is deprecated due to changes in Snapchat's unofficial API."

**Comment by rhpo** [comment]
So there is no way to send snaps again ?
